.section .rodata.ripley_assets,"a",@progbits
.balign 4
.global ripley_bg0_start
.global ripley_bg0_end
ripley_bg0_start:
.incbin "src/assets/bg0.bin"
ripley_bg0_end:
.balign 4
.global ripley_bg1_start
.global ripley_bg1_end
ripley_bg1_start:
.incbin "src/assets/bg1.bin"
ripley_bg1_end:
.balign 4
.global ripley_bg2_start
.global ripley_bg2_end
ripley_bg2_start:
.incbin "src/assets/bg2.bin"
ripley_bg2_end:
.balign 4
.global ripley_bg3_start
.global ripley_bg3_end
ripley_bg3_start:
.incbin "src/assets/bg3.bin"
ripley_bg3_end:
.balign 4
.global ripley_bg4_start
.global ripley_bg4_end
ripley_bg4_start:
.incbin "src/assets/bg4.bin"
ripley_bg4_end:
.balign 4
.global ripley_bg5_start
.global ripley_bg5_end
ripley_bg5_start:
.incbin "src/assets/bg5.bin"
ripley_bg5_end:
.balign 4
.global ripley_bg6_start
.global ripley_bg6_end
ripley_bg6_start:
.incbin "src/assets/bg6.bin"
ripley_bg6_end:
.balign 4
.global ripley_bg7_start
.global ripley_bg7_end
ripley_bg7_start:
.incbin "src/assets/bg7.bin"
ripley_bg7_end:
.balign 4
